In [1]:
import numpy as np

In [3]:
arr1 = np.ones(10) * 5
arr1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
arr2 = np.arange(10, 51)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
arr3 = np.arange(10, 51, 2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
arr4 = np.arange(9).reshape(3, 3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr5 = np.random.randn(25)
arr5

array([ 0.60952205, -1.20948712, -0.67888923,  0.78465865, -1.10185266,
       -1.3810915 ,  0.34242082,  0.21885024,  0.22246703,  0.30881609,
        0.60601745,  0.13648572,  2.07477556, -0.21620454,  0.08925499,
        1.73124525,  1.02553247,  1.22997286, -1.11629159,  1.47070516,
        1.17814259,  0.16052878,  1.55025565,  0.03096003,  1.7409333 ])

In [10]:
arr6 = np.arange(0, 1.01, 0.01)
arr6

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [11]:
arr7 = np.linspace(0, 1, 20)
arr7

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
arr8 = np.arange(1, 26).reshape(5, 5)
arr8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr8[2:5, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
arr8[0:3, 1].reshape(3, 1)

array([[ 2],
       [ 7],
       [12]])

In [20]:
arr8.sum()

325

In [21]:
arr8.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [22]:
arr8.sum(axis=0)

array([55, 60, 65, 70, 75])